server:
  port: 10093
spring:
  cloud:
    tencent:
      # 元数据信息
      metadata:
        content:
          region: huadong
          zone: shanghai
          campus: shanghai1
          version: 1.0.0

#consumer:
#  serviceRouter:
#    plugin:
#      nearbyBasedRouter:
#        #描述: 就近路由的最小匹配级别。region(大区)、zone(区域)、campus(园区)
#        matchLevel: campus
#        #描述: 最大匹配级别
#        maxMatchLevel: all


user:
  age: 22